=== MikeRalphson/atlas/src/main/resources/TVArchive.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited by Gary Bielby "PA" Listings -->
<!-- listings Radio Times DTD v2.10 20/08/2013 mj -->


<!ELEMENT tv_data (archive_update+)>


<!-- the TV listings for a particular date
	date: the date of the listings in the form DD/MM/YYYY, where YYYY indicates the year, MM indicates the month and DD indicates the day -->
<!ELEMENT archive_update (prog_data+)>
<!ATTLIST archive_update
	date CDATA #REQUIRED
>

<!-- the data for a TV programme -->
<!ELEMENT prog_data (showing_id, prog_id, series_id?, series_synopsis?, series_summary?, series_version?, season?, rt_filmnumber?, group?, title, episode_title?, programme_version?, episode_number?, episode_total?, series_number?, category*, rt_category?, film_year?, genre?, certificate?,country?,colour?,warning?,subtitles?,dubbing?,star_rating?, cast_member*, staff_member*, billings?, attr, rovi_genre? ,rovi_description?, links?)>

<!-- generic: This is a generic episode -->
<!ATTLIST prog_data
	generic CDATA #IMPLIED
>


<!-- The id of a showing of a programme on a particular channel. If the time of a showing changes, the showing_id remains the same -->
<!ELEMENT showing_id (#PCDATA)>

<!-- The id of a programme. Different showings of the same programme have the same prog_id. E.g. all showings of a particular episode of Friends have the same prog_id -->
<!ELEMENT prog_id (#PCDATA)>

<!-- The id of a series. E.g. all episodes of Friends have the same series_id -->
<!ELEMENT series_id (#PCDATA)>

<!-- String containing synopsis of series -->
<!ELEMENT series_synopsis (#PCDATA)>

<!-- String containing summary of series -->
<!ELEMENT series_summary (#PCDATA)>


<!-- String to help clarify exactly which series this is in cases where there are other series or programmes with the same title -->
<!ELEMENT series_version (#PCDATA)>

<!-- Season Information -->
<!ELEMENT season (season_title?, season_summary?)>
<!-- id: Unique id for this season -->
<!-- number: The season number -->
<!ATTLIST season
	id CDATA #REQUIRED
	number CDATA #IMPLIED
>

<!-- The Season Title -->
<!ELEMENT season_title (#PCDATA)>

<!-- The Season Summary -->
<!ELEMENT season_summary (#PCDATA)>

<!-- the name of the group this programme belongs to if any -->
<!ELEMENT group (#PCDATA)>

<!-- programme title -->
<!ELEMENT title (#PCDATA)>

<!-- episode title -->
<!ELEMENT episode_title (#PCDATA)>

<!-- String to help clarify exactly which programme this is in cases where there are other programmes or series with the same title -->
<!ELEMENT programme_version (#PCDATA)>

<!-- episode number -->
<!ELEMENT episode_number (#PCDATA)>

<!-- total number of episodes in the series -->
<!ELEMENT episode_total (#PCDATA)>

<!-- series number -->
<!ELEMENT series_number (#PCDATA)>

<!-- rt filmnumber internal ref used by RT -->
<!ELEMENT rt_filmnumber (#PCDATA)>

<!-- programme category -->
<!ELEMENT category (category_name, category_code)>

<!-- RT category -->
<!ELEMENT rt_category (maincat, subcat?)>

<!-- RT Main category -->
<!ELEMENT maincat (#PCDATA)>

<!-- RT Subcategory -->
<!ELEMENT subcat (#PCDATA)>

<!-- programme category name -->
<!ELEMENT category_name (#PCDATA)>

<!-- programme category code -->
<!ELEMENT category_code (#PCDATA)>


<!-- film year (films only) -->
<!ELEMENT film_year (#PCDATA)>


<!-- film certificate (films only) -->
<!ELEMENT certificate (#PCDATA)>

<!-- genre -->
<!ELEMENT genre (#PCDATA)>

<!-- subtitles -->
<!ELEMENT subtitles (#PCDATA)>

<!-- country (films only) -->
<!ELEMENT country (#PCDATA)>

<!-- colour (films only) -->
<!ELEMENT colour (#PCDATA)>

<!-- warning  such as contains strong language -->
<!ELEMENT warning (#PCDATA)>

<!ATTLIST warning
  type CDATA #REQUIRED
>

<!-- Rovi Genre -->
<!ELEMENT rovi_genre (#PCDATA)>

<!-- Rovi Description -->
<!ELEMENT rovi_description (#PCDATA)>


<!-- dubbing  e.g this programme is dubbed in Welsh -->
<!ELEMENT dubbing (#PCDATA)>

<!-- star rating -->
<!ELEMENT star_rating (#PCDATA)>

<!-- cast member -->
<!ELEMENT cast_member (character?, actor?)>

<!-- character in a programme -->
<!ELEMENT character (#PCDATA)>

<!-- production staff member -->
<!ELEMENT staff_member (role, person)>

<!-- production staff role -->
<!ELEMENT role (#PCDATA)>

<!-- an actor in the cast 
person_id: A unique id for this person
-->
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor
	person_id CDATA #REQUIRED
>

<!-- name of member of the production staff 
person_id: A unique id for this person
-->
<!ELEMENT person (#PCDATA)>
<!ATTLIST person
	person_id CDATA #REQUIRED
>
<!-- programme synopsis 
	programme billings such as synopsis, extra detail and x-refs
-->
<!ELEMENT billings (billing+)>

<!--- billing field 
-->
<!ELEMENT billing (#PCDATA)>
<!ATTLIST billing
	type CDATA #REQUIRED
	reviewer_initials CDATA #IMPLIED
	reviewer_name CDATA #IMPLIED
>

<!ELEMENT videoplus (#PCDATA)>

<!-- programme attributes 
	stereo: the programme in stereo.
	subtitles: the programme carries Teletext or Ceefax subtitles.
	repeat: the programme a repeat.
	revised repeat: the programme a revised repeat.
	bw: the programme broadcast in Black and White.
	premiere: this a broadcast premiere.
    new_episode: this is the first showing of this programme on this channel.
    new_series: this is the first episode of a news series of this programme.
	last_in_series: this is the last in a series of showings of this programme.
	surround: the programme is being broadcast in surround sound.
	widescreen: the programme being shown in widescreen format.
	film: the programme a film.
	sign_lang: the programme have sign language.
	in_vision:  the programme has in vision subtitles.
	audio_des: the programme is audio described.
	interactive: the programme has interactive content.
	hd: the programme is also showing on the High Definition channel
	live: this is a live broadcast
	as_live: this programme is being shown as-live
	follow_on: this is a follow_on programme. (The programme follows the previous 
	programme but doesn't have an exact broadcast time). In the xml, the time
	field will contain the time of the previous programme. 
	tv_movie: this programme is a made-for-tv movie
	web_choice: RT web choice
	special: this programme is part of a series but should generally be referred to by the episode title rather than the series title. E.g. "The X-Factor Live Final", "Never Mind the Buzzcocks Christmas Special". E.g. if displaying these programmes on a schedule list, the episode titles should be prominent. 
	three_d: the programme employs techniques of 3D presentation.
	 
-->
<!ELEMENT attr EMPTY>
<!ATTLIST attr
	stereo (yes | no) "no"
	subtitles (yes | no) "no"
	repeat (yes | no) "no"
	revised_repeat (yes | no) "no"
	bw (yes | no) "no"
	premiere (yes | no) "no"
	new_episode (yes | no) "no"
	new_series (yes | no) "no"
	last_in_series (yes | no) "no"
	surround (yes | no) "no"
	widescreen (yes | no) "no"
	film (yes | no) "no"
	sign_lang (yes | no) "no"
	in_vision (yes | no) "no"
	audio_des (yes | no) "no"
	interactive (yes | no) "no"
	hd (yes | no) "no"
	live (yes | no) "no"
	as_live (yes | no) "no"
	follow_on (yes | no) "no"
	choice (yes | no) "no"
	familychoice (yes | no) "no"
	tv_movie (yes | no) "no"
	web_choice (yes | no) "no"
	special (yes | no) "no"
	three_d (yes | no) "no"
>


<!-- Element containing a list links for this showing -->
<!ELEMENT links ( link+ )>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link type (Website | Twitter | email | Phone | Text | Contact) #REQUIRED>

=== MikeRalphson/atlas/src/test/resources/org/atlasapi/remotesite/pa/archives/201601121258_1201_tvarchive.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tv_data SYSTEM "TVArchive.dtd">
<tv_data>
	<archive_update date="2016-01-12">
			<prog_data>
				<showing_id>114733341</showing_id>
				<prog_id>263544</prog_id>
				<rt_filmnumber>5217</rt_filmnumber>
				<title>Star Wars Episode V: the Empire Strikes Back</title>
				<programme_version></programme_version>
				<category><category_name>Science Fiction</category_name><category_code>1300</category_code></category>
                               <category><category_name>Adventure/War</category_name><category_code>1200</category_code></category>
                               <category><category_name>Film</category_name><category_code>BF01</category_code></category>
				<film_year>1980</film_year>
				<genre>Science Fiction</genre>
				<certificate>U</certificate>
				<colour>Colour</colour>
				<star_rating>5</star_rating>
				<cast_member>
						<character>Luke Skywalker</character>
						<actor person_id="10012">Mark Hamill</actor>
				</cast_member>
				<cast_member>
						<character>Han Solo</character>
						<actor person_id="2578">Harrison Ford</actor>
				</cast_member>
				<cast_member>
						<character>Princess Leia</character>
						<actor person_id="584">Carrie Fisher</actor>
				</cast_member>
				<cast_member>
						<character>Lando Calrissian</character>
						<actor person_id="977">Billy Dee Williams</actor>
				</cast_member>
				<cast_member>
						<character>Darth Vader</character>
						<actor person_id="120508">David Prowse/James Earl Jones (voice)</actor>
				</cast_member>
				<cast_member>
						<character>Obi-Wan Kenobi</character>
						<actor person_id="4751">Alec Guinness</actor>
				</cast_member>
				<cast_member>
						<character>C-3PO</character>
						<actor person_id="5870">Anthony Daniels</actor>
				</cast_member>
				<cast_member>
						<character>Chewbacca</character>
						<actor person_id="29439">Peter Mayhew</actor>
				</cast_member>
				<cast_member>
						<character>R2-D2</character>
						<actor person_id="10796">Kenny Baker</actor>
				</cast_member>
				<cast_member>
						<character>Yoda</character>
						<actor person_id="120509">Frank Oz (voice)</actor>
				</cast_member>
				<cast_member>
						<character>Boba Fett</character>
						<actor person_id="22162">Jeremy Bulloch</actor>
				</cast_member>
				<cast_member>
						<character>Admiral Piett</character>
						<actor person_id="5776">Kenneth Colley</actor>
				</cast_member>
				<cast_member>
						<character>Admiral Ozzel</character>
						<actor person_id="17580">Michael Sheard</actor>
				</cast_member>
				<cast_member>
						<character>Gen Veers</character>
						<actor person_id="9549">Julian Glover</actor>
				</cast_member>
				<cast_member>
						<character>Wedge Antilles</character>
						<actor person_id="11355">Denis Lawson</actor>
				</cast_member>
				<staff_member>
					<role>Director</role>
					<person person_id="4135">Irvin Kershner</person>
				</staff_member>
				<billings>
					<billing type="synopsis">The rebels are scattered across the galaxy after the Empire launches a devastating attack on their secret base. Luke Skywalker searches out a Jedi master to complete his training, while Han Solo and Princess Leia are relentlessly pursued by Darth Vader&apos;s space fleet. Sci-fi adventure sequel, with Harrison Ford, Mark Hamill, Carrie Fisher, Billy Dee Williams, Alec Guinness and David Prowse.</billing>
					<billing type="pa_detail1">Sci-fi adventure sequel, with Mark Hamill and Harrison Ford.</billing>
					<billing type="pa_detail2">The rebels are dispersed after an attack on their secret base and Luke Skywalker goes in search of a Jedi master. Sci-fi adventure sequel, starring Mark Hamill and Harrison Ford.</billing>
					<billing type="pa_detail3">The rebels are scattered across the galaxy after the Empire launches a devastating attack on their secret base. Luke Skywalker searches out a Jedi master to complete his training, while Han Solo and Princess Leia are relentlessly pursued by Darth Vader&apos;s space fleet. Sci-fi adventure sequel, with Harrison Ford, Mark Hamill, Carrie Fisher, Billy Dee Williams, Alec Guinness and David Prowse.</billing>
				</billings>
<attr stereo="no" subtitles="no" repeat="no" revised_repeat="no" bw="no" premiere="no" new_episode="no" new_series="no" last_in_series="no" surround="no" widescreen="no" film="yes" sign_lang="no" in_vision="no" audio_des="no" interactive="no" hd="no" live="no" as_live="no" follow_on="no" tv_movie="no" special="no" three_d="no"/>
			</prog_data>
			<prog_data>
				<showing_id>114733406</showing_id>
				<prog_id>1769784</prog_id>
				<series_id>56277</series_id>
				<series_synopsis>Arts documentary</series_synopsis>
				<series_summary>&apos;Imagine&apos; is a BBC arts show covering a wide variety of topics, each series usually consisting of four to seven episodes. It is hosted by Alan Yentob. Past subjects have included Stella McCartney, John Mortimer, British and American sitcoms, Edward Hopper, Marlon Brando, Roald Dahl, Peter Pan, operatic divas, modern children&apos;s fiction, Gilbert and George, Richard Rodgers, Anthony Minghella, Jay-Z, David Hockney, Shirley Bassey, and John Lennon. It premiered on BBC One in 2003.</series_summary>
				<season id="28515" number="22">
					<season_title>Imagine Season 22</season_title>
				</season>
				<title>Imagine</title>
				<episode_title>David Bowie: Cracked Actor - An Imagine Special</episode_title>
				<programme_version></programme_version>
				<episode_number>2</episode_number>
				<episode_total>2</episode_total>
				<series_number>22</series_number>
				<category><category_name>Documentary</category_name><category_code>2300</category_code></category>
                               <category><category_name>General Arts/Culture</category_name><category_code>7000</category_code></category>
                               <category><category_name>General Music/Ballet/Dance</category_name><category_code>6000</category_code></category>
				<genre>Documentary</genre>
				<colour>Colour</colour>
				<staff_member>
					<role>Director</role>
					<person person_id="66391">Alan Yentob</person>
				</staff_member>
				<staff_member>
					<role>Executive Producer</role>
					<person person_id="95657">Carol Bell</person>
				</staff_member>
				<staff_member>
					<role>Producer</role>
					<person person_id="66391">Alan Yentob</person>
				</staff_member>
				<billings>
					<billing type="synopsis">To mark David Bowie&apos;s return to the music scene after a 10-year hiatus and a new exhibition at the Victoria and Albert Museum, here is another chance to see Alan Yentob&apos;s documentary following the musician across America on his 1974 Diamond Dogs tour, at a time when his rock star excesses were at their most extreme. Originally shown as part of Omnibus in 1975, the film features revealing footage of Bowie and his fans, illustrating the effects of fame on musicians and their followers.</billing>
					<billing type="pa_detail1">Documentary following David Bowie on his 1974 Diamond Dogs tour.</billing>
					<billing type="pa_detail2">Alan Yentob&apos;s seminal documentary, originally shown as part of Omnibus in 1975, following David Bowie across America on his 1974 Diamond Dogs tour.</billing>
					<billing type="pa_detail3">To mark David Bowie&apos;s return to the music scene after a 10-year hiatus and a new exhibition at the Victoria and Albert Museum, here is another chance to see Alan Yentob&apos;s documentary following the musician across America on his 1974 Diamond Dogs tour, at a time when his rock star excesses were at their most extreme. Originally shown as part of Omnibus in 1975, the film features revealing footage of Bowie and his fans, illustrating the effects of fame on musicians and their followers.</billing>
				</billings>
<attr stereo="no" subtitles="no" repeat="no" revised_repeat="no" bw="no" premiere="no" new_episode="no" new_series="no" last_in_series="no" surround="no" widescreen="no" film="no" sign_lang="no" in_vision="no" audio_des="no" interactive="no" hd="no" live="no" as_live="no" follow_on="no" tv_movie="no" special="yes" three_d="no"/>
			</prog_data>
			<prog_data>
				<showing_id>114733463</showing_id>
				<prog_id>588413</prog_id>
				<title>Story of David Bowie</title>
				<programme_version></programme_version>
				<category><category_name>General Music/Ballet/Dance</category_name><category_code>6000</category_code></category>
				<genre>General Music/Ballet/Dance</genre>
				<colour>Colour</colour>
				<billings>
					<billing type="synopsis">The story and success of David Bowie.</billing>
					<billing type="pa_detail1">The story and success of David Bowie.</billing>
				</billings>
<attr stereo="no" subtitles="no" repeat="no" revised_repeat="no" bw="no" premiere="no" new_episode="no" new_series="no" last_in_series="no" surround="no" widescreen="no" film="no" sign_lang="no" in_vision="no" audio_des="no" interactive="no" hd="no" live="no" as_live="no" follow_on="no" tv_movie="no" special="no" three_d="no"/>
			</prog_data>
	</archive_update>
</tv_data>
